# Staging environment

global:
  namespace: foodmission-staging
  environment: staging
  tlsSecret: foodmission-tls-cert-staging
  cnpg:
    clusterName: foodmission-pg-staging

cnpg:
  instances: 3
  storageSize: 10Gi

  backup:
    enabled: true
    barmanStoreName: foodmission-backup-store
    destinationPath: s3://foodmission-staging/backups
    endpointURL: https://hel1.your-objectstorage.com

  scheduledBackup:
    enabled: true

  #   # Bootstrap from existing backup
  # bootstrap:
  #   recovery:
  #     source: foodmission-pg-staging

  # # Define the external cluster (the backup source)
  # externalClusters:
  #   - name: foodmission-pg-staging
  #     barmanObjectStore:
  #       destinationPath: s3://foodmission-staging/backups
  #       endpointURL: https://hel1.your-objectstorage.com
  #       serverName: foodmission-pg # new one is foodmission-pg-staging
  #       s3Credentials:
  #         accessKeyId:
  #           name: foodmission-secrets
  #           key: ACCESS_KEY_ID
  #         secretAccessKey:
  #           name: foodmission-secrets
  #           key: ACCESS_SECRET_KEY
  #       wal:
  #         compression: gzip

api:
  image: ghcr.io/reedu-reengineering-education/foodmission-data-framework:0.2.3
  hostname: staging.api.foodmission.eu
  replicaCount: 3
  extraEnv:
    - name: MONGODB_OFF_URL
      value: "mongodb://admin:TestPassword123@mongodb-service.off-test.svc.cluster.local:27017/?authSource=admin"
  translations:
    enabled: true
  opentelemetry:
    enabled: "true"

keycloak:
  image: ghcr.io/reedu-reengineering-education/foodmission-keycloak:0.1.2
  hostname: staging.auth.foodmission.eu
  replicaCount: 2

valkey:
  enabled: true