apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: foodmission

  source:
    repoURL: https://github.com/reedu-reengineering-education/foodmission-infra.git
    targetRevision: main
    path: charts/observability
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # needed for large CRDs (Prometheus rules etc.)
