apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foodmission-prod
  namespace: argocd
spec:
  project: foodmission

  sources:
    # Helm chart
    - repoURL: https://github.com/reedu-reengineering-education/foodmission-infra.git
      targetRevision: main
      path: charts/foodmission
      helm:
        valueFiles:
          - values.yaml
          - prod.values.yaml
    # SealedSecrets
    - repoURL: https://github.com/reedu-reengineering-education/foodmission-infra.git
      targetRevision: main
      path: secrets
      directory:
        include: 'prod.sealed.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: foodmission-prod

  syncPolicy:
    automated:
      prune: false     # protect database from accidental deletion
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
