apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: manual-backup-pre-migration
  namespace: foodmission-staging
spec:
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: foodmission-pg-staging
