---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBwRjQj3Sse3jQYNTG3X4GK1n0ZT0y+WZYAFimBQURUEZOjCDYbq06c5PPQGwbMZDuHE7eCGnj6RTheOLEjIxwpOQiZXdIMgXs9uQ/NYtB+0FVZw+rgkQ9J6jOr9EYMLf+xyup6apVh2V5SwQqAUDdMt+98XKgPZWsmG7NhJXP8rS0X3wlyuC5P1I0D0jecMCPQe6rMwrWTKCJZP2O5rM8RBWwxPLIJ191U39YqwKY/wey6ILAzaHAZeFHAhhgVkI5/n7vdGzQxqwx3Ae5Hz+2JqZ3T2ex+Yd84c55s4dxnH+Bdgq8kTyUM3+pRWFYp4M8H8t0SXqDVwpHz0l8AKnDGVvF/YSog27w3y2LCFmsOnBUeB/Bbp7cQgXVhDxqxKL+3pviX2lc1V/AArTp4NrlYpZr9rz/luezS3O1gV9IvOZdxuHZqFR9uQeVzsgODGlPzFxADfufn+OxXqZy90ELLdFkCqOcOp7qsYFO3suAv6moW6FGU7afZehihOR5buvQKogm6dkW6aRklriCg9rPDodaFsJ9xWc2vE3tLoqHdwQ+cllLz8DPJ1JfAujxUJvs6dPcALT7m6clX4Uuo92NU2dojllsGK50STGwxQR7PFvbUXVIw3YWo6nOyWFce93ZMH0Jiw2pHBenOhpTos9ZxvsWG0UD+bGPM5p09d8U0ETXPp+LIRpMWENil1jW/whhVBFIkei35MESqASY7I3OyIyRKMEmEAhJMYJ8D4AH+mw==
    admin-user: AgB+49WJ63nqC3vuaKgoV3m82/ZJKxcgw9MitBbu+x4inmW39srrTXYlY6dr/jyNfsOeyH5W1fs0nHdfoFEttpS0rKAULFpRg/SGbdAvIxuC5FR/Lbpj4iLi4kb+jJmVVQUZ7NNbooerbq9eIMljYnY2zcLSvFOzqGHOqguC2JptUMA1+WXOBXO/ke4gX0cWbiE3UGcQx92hZNx1IMmxt47OMmCGqS0qwiggv31AzVTy7LLR9goHnYqgGUJnzh+ntslxCQMfkNoJHxKZDeBymPQcYS1cA6/EuEXaw3hbXjnxm/QlIa0gwa3XnU5bD76uE/3HvyMgKJFlTdzRuQw2g3NvMqM8DnXGqvue52ElNg6cv0bXXJRbdg4isYnU7XhYkKjP7r6zYq9GrO/UGtdHcjGxLa/K2nr4LlyjdHYYwBbkInyemLf6nNpTskFpsDvxdf5VqglpHq6GsHrHp96pFOvEVfPecmpK9nPOtkdvxU4g4BuibyzMAu7iGo/K/tzjyZ0kpNuYOmhURxUMMr8HhxDEU9JqsnmAoxLfN18gWzPO25lB19qGGPHQiY8cIOLvKfaJRE6leMm4ip/39Vp8CY6+QNh+Lz4wGXW8Dzgw1mlkiiqCJ02SCkl3S5JB2VBTyPuXjIcLAs3+DtREfssREYOUtKAUPlMwrx/4pwK4pHDUtQKMtsRHQ1p4sYVJYVfcFKwUC1NDbQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: observability
    type: Opaque
